import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header>
      <div className="text-yellow-400 auto-cols-auto bg-black p-4 fixed top-0 right-0 left-0">
        <p className="float-left m-2">Force Doctrine</p>
        <nav className="flex flex-row-reverse md:[&>*]:mx-4">
          <Link href="/login"><button className="text-black bg-red-500 hover:bg-red-600 focus:outline-2 focus:outline-offset-2 focus:outline-red-500 active:bg-red-700 rounded-lg m-1 p-1 px-2">Log in</button></Link>
          <Link href="/about" className="m-2">About</Link>
          <Link href="/techniques" className="m-2">Techniques</Link>
          <Link href="/" className="m-2">Home</Link>
        </nav>
      </div>
    </header>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-black">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
