import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header>
      <div className="text-yellow-400 auto-cols-auto bg-black">
        <nav>
          <div>
            <Link href="/">Home</Link>
          </div>
          <div>
            <Link href="/techniques">Techniques</Link>
          </div>
          <div>
            <Link href="/about">About</Link>
          </div>
          <div className="bg-red-500">
            <Link href="/login">Log in</Link>
          </div>
        </nav>
      </div>
    </header>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
